name: dependencies-test 

on:
  workflow_dispatch:


      #   env:
      #     super_secret: ${{ secrets.SUPERSECRET }}
      #   needs:
      #     setup_dependencies
      
      # services:
      #   postgres:
      #     image: postgres
     
      # env:
      #   POSTGRES_HOST: postgres
      #   POSTGRES_PORT: 5432

jobs:
  install-dependencies:
    strategy:
      matrix:
        node_version: ['10', '12']
        os: [ubuntu-latest, windows-latest, macOS-latest]
    runs-on: ${{ matrix.os }}
    steps:

      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}

      - name: use cache 
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ matrix.node_version }}-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm install

      - name: use cache 
        uses: actions/cache@v2
        with:
          path: '*' 
          key: ${{ runner.os }}-${{ matrix.node_version }}-${{ env.GITHUB_RUN_ID }}

  integration-tests:
    needs: install-dependencies
    strategy:
      matrix:
        node_version: ['10', '12']
        os: [ubuntu-latest, windows-latest, macOS-latest]
    runs-on: ${{ matrix.os }}
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USERNAME: postgres
          POSTGRES_PASSWORD: postgres
    steps:
      - name: use cache 
        uses: actions/cache@v2
        with:
          path: '*' 
          key: ${{ runner.os }}-${{ matrix.node_version }}-${{ env.GITHUB_RUN_ID }}

      - name: Run unit tests 
        run: npm test