name: dependencies-test 

on:
  pull_request:
    branches: [ main ]


      #   env:
      #     super_secret: ${{ secrets.SUPERSECRET }}
      #   needs:
      #     setup_dependencies
      
      # services:
      #   postgres:
      #     image: postgres
     
      # env:
      #   POSTGRES_HOST: postgres
      #   POSTGRES_PORT: 5432

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v2

      - name: Set up node
        uses: actions/setup-node@v1

      - name: Install dependencies
        run: npm install

      - name: Run unit tests
        run: npm run test:unit

  integration-tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USERNAME: postgres
          POSTGRES_PASSWORD: postgres
    steps:
      - name: Check out source code
        uses: actions/checkout@v2

      - name: Set up node
        uses: actions/setup-node@v1

      - name: Install dependencies
        run: npm install

      - name: Run integration tests
        run: npm run test:integration
        env:
          POSTGRES_HOST: my-postgres-container
          POSTGRES_PASSWORD: postgres